name: test

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight

  workflow_run:
    workflows: ['lint-code']
    types:
      - completed

  push:
    branches:
      - develop
      - main

  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    name: test
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: check out a copy of the repo
        uses: actions/checkout@v2

      - name: install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: test
        run: go test ./...
